version: 0.2

env:
  shell: "/bin/sh"
  variables:
    IMAGE_TAG: registration-service
    slack_webhook_url: https://hooks.slack.com/services/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
  parameter-store:
    ECR_REGISTRY_URI: ecr-registry-uri
    AWS_DEFAULT_REGION: default-region-aws
phases:
  install:
    runtime-versions:
      php: 8.2

  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY_URI
      - echo Installation of Trivy...
      - echo Installation of Trivy...
      - yum install rpm
      - rpm -ivh https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.rpm
      - trivy -v version
 
  
      
  build:
    commands:
      - docker load -i docker-image.tar.gz
      - image_id=$(docker images --format "{{.ID}}" | head -n 1)
      - docker tag $image_id $ECR_REGISTRY_URI:$IMAGE_TAG
      
      
      
     
  post_build:
    commands:
    - echo Docker Image Scanning...
    - trivy image --severity HIGH,CRITICAL $ECR_REGISTRY_URI:$IMAGE_TAG > trivy_scan.log
    - aws s3 cp trivy_scan.log s3://vaccination-pipeline-artifactstore/reports/Trivy/trivy_scan.$CODEBUILD_BUILD_ID.log
    # - chmod +x trivy-report.sh
    # - ./trivy-report.sh
    - echo "scanning"
    - curl -X POST -H 'Content-type: application/json' --data '{"text":"This is a test message"}' "$slack_webhook_url"
    - echo "done"


       
       

    
privilegedMode: true
